ALTER TABLE observations ADD COLUMN IF NOT EXISTS wind_gust DOUBLE PRECISION;
ALTER TABLE observations ADD COLUMN IF NOT EXISTS dew_point DOUBLE PRECISION;
ALTER TABLE observations ADD COLUMN IF NOT EXISTS precip_1h DOUBLE PRECISION;
ALTER TABLE observations ADD COLUMN IF NOT EXISTS precip_intensity DOUBLE PRECISION;
ALTER TABLE observations ADD COLUMN IF NOT EXISTS snow_depth DOUBLE PRECISION;
ALTER TABLE observations ADD COLUMN IF NOT EXISTS visibility DOUBLE PRECISION;
ALTER TABLE observations ADD COLUMN IF NOT EXISTS total_cloud_cover DOUBLE PRECISION;
ALTER TABLE observations ADD COLUMN IF NOT EXISTS weather_code DOUBLE PRECISION;
ALTER TABLE observations ADD COLUMN IF NOT EXISTS extra JSONB;
