ALTER TABLE hourly_forecasts ADD COLUMN IF NOT EXISTS wind_gust DOUBLE PRECISION;
ALTER TABLE hourly_forecasts ADD COLUMN IF NOT EXISTS pressure DOUBLE PRECISION;
ALTER TABLE hourly_forecasts ADD COLUMN IF NOT EXISTS cloud_cover DOUBLE PRECISION;
