ALTER TABLE daily_climate_normals
    ADD COLUMN IF NOT EXISTS feels_like_avg     DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS feels_like_high    DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS feels_like_low     DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS wind_avg           DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS wind_gust          DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS humidity_avg       DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS precip_days_pct    DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS snow_cm            DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS feels_like_hourly  DOUBLE PRECISION[],
    ADD COLUMN IF NOT EXISTS wind_hourly        DOUBLE PRECISION[],
    ADD COLUMN IF NOT EXISTS humidity_hourly    DOUBLE PRECISION[],
    ADD COLUMN IF NOT EXISTS temp_hourly_p10    DOUBLE PRECISION[],
    ADD COLUMN IF NOT EXISTS temp_hourly_p90    DOUBLE PRECISION[];
