ALTER TABLE forecasts
    ADD COLUMN IF NOT EXISTS feels_like_high DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS feels_like_low  DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS feels_like_avg  DOUBLE PRECISION;
